name: Preflight

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: ESLint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow@eslint

  typecheck:
    name: Typecheck
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow@typecheck

  playwright:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow@playwright
