name: Release

on:
  push:
    branches: [main]

jobs:
  eslint:
    name: ESLint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/eslint@main

  typecheck:
    name: Typecheck
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/typecheck@main

  playwright:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/playwright@main

  release:
    name: Release
    needs: ['eslint', 'typecheck', 'playwright']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/release@main

  publish:
    name: Publish
    needs: ['eslint', 'typecheck', 'playwright', 'release']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/publish@main
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
