name: Release

on:
  push:
    branches: [main]

jobs:
  eslint3:
    name: ESLint3
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/eslint

  typecheck3:
    name: Typecheck3
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/typecheck

  playwright3:
    name: Playwright3
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/playwright

  release3:
    name: Release3
    needs: ['eslint3', 'typecheck3', 'playwright3']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/release

  publish3:
    name: Publish3
    needs: ['eslint3', 'typecheck3', 'playwright3', 'release3']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/publish
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
