name: Release

on:
  push:
    branches: [release]

jobs:
  eslint:
    name: ESLint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/eslint@main

  typecheck:
    name: Typecheck
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/typecheck@main

  playwright:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/playwright@main

  release:
    if: ${{ !contains(github.event.head_commit.message, '~sync') }}
    name: Release
    needs: ['eslint', 'typecheck', 'playwright']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/release@main

  postRelease:
    if: ${{ !contains(github.event.head_commit.message, '~sync') }}
    name: Post release
    needs: ['eslint', 'typecheck', 'playwright', 'release']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/postRelease@main
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
          github_token: ${{ secrets.GITHUB_TOKEN}}
