name: Release

on:
  push:
    branches: [main]

jobs:
  eslint:
    name: ESLint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/eslint

  typecheck:
    name: Typecheck
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/typecheck

  playwright:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/playwright

  release:
    name: Release
    needs: ['eslint', 'typecheck', 'playwright']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/release

  publish:
    name: Publish
    needs: ['eslint', 'typecheck', 'playwright', 'release']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/publish
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
